export const SITE = {
  name: 'Villanymester',
  tagline: 'Megbízható villanyszerelő Pest megyében',
  domain: 'mateklap.hu',
  url: 'https://mateklap.hu',
  phone: '+36 70 293 3659',
  phoneDisplay: '+36 70 293 3659',
  email: 'info@mateklap.hu',
  address: 'Érd, Pest megye',
  founded: '2015',
  logo: '/logo.svg',
  description: 'Profi villanyszerelési szolgáltatások Pest megyében. Érd, Gödöllő, Dunakeszi, Szentendre, Vác és környéke. Gyors kiszállás, megbízható munka, díjmentes árajánlat.',
}

export const CITIES = [
  {
    slug: 'villanyszerelo-erd',
    suffixOn: 'Érden',
    suffixAdj: 'érdi',
    name: 'Érd',
    county: 'Pest megye',
    population: '70 000',
    mainKeyword: 'villanyszerelő Érd',
    searchVolume: 260,
    districts: ['Érd-Óváros', 'Érd-Parkváros', 'Érd-Ciprusdomb', 'Érd-Újváros'],
    description: 'Pest megye legnépesebb városa, 70 000+ lakos, aktív ingatlanpiac.',
    localFact: 'Érd Pest megye legnépesebb városa közel 70 000 lakossal. Az M0-ás és a 6-os főút mentén elhelyezkedő városban az ingatlanfejlesztések és felújítások folyamatosak.',
    h1: 'Villanyszerelő Érden – Gyors, Megbízható Elektromos Munkák',
    metaTitle: 'Villanyszerelő Érd ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Profi villanyszerelő Érden ✓ Hibaelhárítás, töltő telepítés, felújítás ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most: +36 70 293 3659',
    faqs: [
      { q: 'Milyen gyorsan tud kiszállni villanyszerelő Érden?', a: 'Sürgős megkeresések esetén általában 2-4 órán belül kiszállunk Érd területén. Normál esetben 24 órán belül időpontot tudunk egyeztetni.' },
      { q: 'Mennyibe kerül a villanyszerelés Érden?', a: 'Az árak az elvégzett munka típusától függnek. Hibaelhárítás 15 000 Ft-tól, lakás villanyszerelés 800-1200 Ft/m² áron. Részletes díjmentes árajánlatot adunk.' },
      { q: 'Vállalnak elektromos autó töltő telepítést Érden?', a: 'Igen, a töltő telepítés az egyik legkeresettebb szolgáltatásunk Érden. 11 kW-os fali töltőt 120 000-180 000 Ft-tól telepítünk.' },
      { q: 'Érd melyik részére szállnak ki?', a: 'Érd összes városrészére kiszállunk: Óváros, Parkváros, Ciprusdomb, Újváros és minden érintett terület.' },
      { q: 'Rendelkeznek villanyszerelői engedéllyel?', a: 'Igen, minden munkatársunk rendelkezik a szükséges villanyszerelői képesítéssel és engedéllyel. Munkáinkhoz tűzvédelmi és elektromos bejelentési dokumentumokat adunk.' },
    ],
  },
  {
    slug: 'villanyszerelo-godollö',
    suffixOn: 'Gödöllőn',
    suffixAdj: 'gödöllői',
    name: 'Gödöllő',
    county: 'Pest megye',
    population: '35 000',
    mainKeyword: 'villanyszerelő Gödöllő',
    searchVolume: 190,
    districts: ['Gödöllő belváros', 'Máriabesnyő', 'Erzsébetkert', 'Dózsa György lakótelep'],
    description: 'Élénk egyetemi város, Grassalkovich-kastély, sok felújítandó ingatlan.',
    localFact: 'Gödöllő a Grassalkovich-kastélyáról és a MATE Gödöllői Kampuszáról ismert város. Az élénk ingatlanpiac és a sok régi, felújítandó épület folyamatos elektromos munkákat generál.',
    h1: 'Villanyszerelő Gödöllőn – Profi Elektromos Munkák Garanciával',
    metaTitle: 'Villanyszerelő Gödöllő ✓ Azonnali Kiszállás | Villanymester Kft.',
    metaDescription: 'Megbízható villanyszerelő Gödöllőn ✓ Felújítás, hibaelhárítás, töltő telepítés ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Mennyibe kerül a villanyszerelés Gödöllőn?', a: 'Hibaelhárítás 15 000 Ft-tól, teljes lakás villanyszerelés 800-1200 Ft/m²-től. Részletes ingyenes árajánlatot adunk.' },
      { q: 'Gödöllő melyik részére szállnak ki?', a: 'Gödöllő egész területére kiszállunk: belváros, Máriabesnyő, Erzsébetkert és minden egyéb városrész.' },
      { q: 'Vállalnak munkát régi gödöllői házakban is?', a: 'Igen, tapasztaltak vagyunk régi elektromos rendszerek felújításában és korszerűsítésében.' },
      { q: 'Milyen gyorsan érnek ki Gödöllőre?', a: 'Sürgős esetben 2-4 órán belül, normál esetben 24 órán belüli időpontot tudunk adni.' },
      { q: 'Vállalnak napelem bekötést Gödöllőn?', a: 'Igen, napelem rendszerek villanyszerelési munkáit vállaljuk: bekötés, védelem telepítése, hálózati csatlakozás.' },
    ],
  },
  {
    slug: 'villanyszerelo-dunakeszi',
    suffixOn: 'Dunakeszin',
    suffixAdj: 'dunakeszi',
    name: 'Dunakeszi',
    county: 'Pest megye',
    population: '42 000',
    mainKeyword: 'villanyszerelő Dunakeszi',
    searchVolume: 210,
    districts: ['Dunakeszi belváros', 'Alag', 'Dunakeszi-Gyártelep', 'Tőzeges'],
    description: 'Dinamikusan fejlődő Duna-parti város, sok új lakópark és fejlesztés.',
    localFact: 'Dunakeszi az egyik legdinamikusabban fejlődő Pest megyei város, ahol folyamatosan épülnek új lakóparkok és irodaházak.',
    h1: 'Villanyszerelő Dunakeszin – Új Építés és Felújítás Specialista',
    metaTitle: 'Villanyszerelő Dunakeszi ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Profi villanyszerelő Dunakeszin ✓ Új építés, felújítás, töltő telepítés ✓ Gyors kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Vállalnak új építésű projektet Dunakeszin?', a: 'Igen, az új építések villanyszerelése az egyik fő szakterületünk Dunakeszin és környékén.' },
      { q: 'Mennyibe kerül a villanyszerelés Dunakeszin?', a: 'Hibaelhárítás 15 000 Ft-tól, új épület villanyszerelés 900-1400 Ft/m²-től. Ingyenes helyszíni felmérést végzünk.' },
      { q: 'Milyen gyorsan lehet időpontot kapni Dunakeszin?', a: 'Sürgős esetben 2-4 óra, normál esetben 24 órán belül.' },
      { q: 'Vállalnak elektromos autó töltő telepítést Dunakeszin?', a: 'Igen, társasházi és egyéni töltő telepítése is a szolgáltatásaink között van.' },
      { q: 'Dunakeszi melyik részére szállnak ki?', a: 'Dunakeszi teljes területére: belváros, Alag, Gyártelep, Tőzeges és minden városrész.' },
    ],
  },
  {
    slug: 'villanyszerelo-szentendre',
    suffixOn: 'Szentendrén',
    suffixAdj: 'szentendrei',
    name: 'Szentendre',
    county: 'Pest megye',
    population: '26 000',
    mainKeyword: 'villanyszerelő Szentendre',
    searchVolume: 170,
    districts: ['Szentendre belváros', 'Izbég', 'Pannónia utca negyed', 'Pismány'],
    description: 'Festői Duna-parti kisváros, sok régi épület és műemlék, turisztikai célpont.',
    localFact: 'Szentendre festői kisváros a Duna-kanyarban, sok régi, felújítandó épülettel.',
    h1: 'Villanyszerelő Szentendrén – Régi és Új Épületek Specialistája',
    metaTitle: 'Villanyszerelő Szentendre ✓ Régi Házak Specialistája | Villanymester',
    metaDescription: 'Megbízható villanyszerelő Szentendrén ✓ Régi épületek felújítása ✓ Gyors kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Dolgoznak régi szentendrei házakban is?', a: 'Igen, tapasztaltak vagyunk műemlékes épületek elektromos rendszereinek felújításában.' },
      { q: 'Mennyibe kerül a villanyszerelés Szentendrén?', a: 'Hibaelhárítás 15 000 Ft-tól, felújítás 900-1300 Ft/m²-től.' },
      { q: 'Milyen gyorsan érnek ki Szentendrére?', a: 'Sürgős esetben 2-4 óra, egyébként 24 órán belüli időpont.' },
      { q: 'Vállalnak napelem bekötést Szentendrén?', a: 'Igen, napelem rendszerek bekötése és hálózati csatlakoztatása.' },
      { q: 'Szentendre melyik részére szállnak ki?', a: 'Szentendre teljes területére: belváros, Izbég, Pismány és minden városrész.' },
    ],
  },
  {
    slug: 'villanyszerelo-vac',
    suffixOn: 'Vácon',
    suffixAdj: 'váci',
    name: 'Vác',
    county: 'Pest megye',
    population: '34 000',
    mainKeyword: 'villanyszerelő Vác',
    searchVolume: 150,
    districts: ['Vác belváros', 'Deákvár', 'Hétkápolna', 'Alsóváros'],
    description: 'Történelmi barokk belváros, ipari múlttal rendelkező Duna-parti város.',
    localFact: 'Vác gazdag történelmi barokk belvárossal rendelkező Duna-parti város.',
    h1: 'Villanyszerelő Vácon – Ipari és Lakóingatlan Szakértők',
    metaTitle: 'Villanyszerelő Vác ✓ Ipari és Lakás Villanyszerelés | Villanymester',
    metaDescription: 'Profi villanyszerelő Vácon ✓ Ipari és lakóingatlan villanyszerelés ✓ Gyors kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Vállalnak ipari villanyszerelést Vácon?', a: 'Igen, ipari és kereskedelmi ingatlanok villanyszerelése is a szakterületünk.' },
      { q: 'Mennyibe kerül a villanyszerelés Vácon?', a: 'Lakás villanyszerelés 800-1200 Ft/m²-től, ipari munkák egyedi árajánlat alapján.' },
      { q: 'Milyen gyorsan érnek ki Vácra?', a: 'Sürgős esetben 2-4 óra, normál esetben 24 órán belüli időpont.' },
      { q: 'Foglalkoznak régi váci épületekkel?', a: 'Igen, régi és műemlékes épületek elektromos felújítása is vállalt munkakörünk.' },
      { q: 'Vác melyik részére szállnak ki?', a: 'Vác teljes területére: belváros, Deákvár, Hétkápolna, Alsóváros.' },
    ],
  },
  {
    slug: 'villanyszerelo-dunaharaszti',
    suffixOn: 'Dunaharasztiban',
    suffixAdj: 'dunaharaszti',
    name: 'Dunaharaszti',
    county: 'Pest megye',
    population: '22 000',
    mainKeyword: 'villanyszerelő Dunaharaszti',
    searchVolume: 210,
    districts: ['Dunaharaszti belváros', 'Király-hegy', 'Dunapart', 'Soroksári út'],
    description: 'Dunai kisváros, dinamikusan növekvő lakossággal, sok új építés.',
    localFact: 'Dunaharaszti Pest megye egyik legdinamikusabban fejlődő kisvárosában az új lakóparkok folyamatos elektromos munkákat generálnak.',
    h1: 'Villanyszerelő Dunaharasztiban – Gyors Kiszállás, Fix Árak',
    metaTitle: 'Villanyszerelő Dunaharaszti ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Profi villanyszerelő Dunaharasztiban ✓ Hibaelhárítás, felújítás, töltő telepítés ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Milyen gyorsan tud kiszállni villanyszerelő Dunaharasztiban?', a: 'Sürgős esetben 2-4 órán belül, normál esetben 24 órán belül.' },
      { q: 'Mennyibe kerül a villanyszerelés Dunaharasztiban?', a: 'Hibaelhárítás 15 000 Ft-tól, lakás villanyszerelés 800-1200 Ft/m²-től.' },
      { q: 'Vállalnak új építést Dunaharasztiban?', a: 'Igen, új lakóparkok és házak villanyszerelése is a szakterületünk.' },
      { q: 'Dunaharaszti melyik részeire szállnak ki?', a: 'Dunaharaszti teljes területére kiszállunk.' },
      { q: 'Rendelkeznek engedéllyel?', a: 'Igen, minden munkatársunk rendelkezik a szükséges képesítéssel és engedéllyel.' },
    ],
  },
  {
    slug: 'villanyszerelo-budaors',
    suffixOn: 'Budaörsön',
    suffixAdj: 'budaorsi',
    name: 'Budaörs',
    county: 'Pest megye',
    population: '32 000',
    mainKeyword: 'villanyszerelő Budaörs',
    searchVolume: 90,
    districts: ['Budaörs belváros', 'Frankhegy', 'Kamaraerdei út', 'Hosszúrét'],
    description: 'Budapest agglomeráció egyik leggazdagabb városa, sok üzleti park.',
    localFact: 'Budaörs Budapest agglomerációjának egyik legdinamikusabb városa irodaparkok és lakóparkok területén.',
    h1: 'Villanyszerelő Budaörsön – Profi Elektromos Munkák',
    metaTitle: 'Villanyszerelő Budaörs ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Megbízható villanyszerelő Budaörsön ✓ Lakásfelújítás, hibaelhárítás ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Milyen gyorsan érnek ki Budaörsre?', a: 'Sürgős esetben 2-4 óra, egyébként 24 órán belül.' },
      { q: 'Mennyibe kerül a villanyszerelés Budaörsön?', a: 'Hibaelhárítás 15 000 Ft-tól, felújítás 900-1300 Ft/m²-től.' },
      { q: 'Vállalnak irodaházi munkákat Budaörsön?', a: 'Igen, irodai és üzleti ingatlanok villanyszerelése is vállalt munkánk.' },
      { q: 'Budaörs melyik részeire szállnak ki?', a: 'Budaörs teljes területére kiszállunk.' },
      { q: 'Rendelkeznek engedéllyel?', a: 'Igen, minden munkatársunk rendelkezik a szükséges képesítéssel.' },
    ],
  },
  {
    slug: 'villanyszerelo-torokbalint',
    suffixOn: 'Törökbálinton',
    suffixAdj: 'torokbalinti',
    name: 'Törökbálint',
    county: 'Pest megye',
    population: '16 000',
    mainKeyword: 'villanyszerelő Törökbálint',
    searchVolume: 50,
    districts: ['Törökbálint belváros', 'Torbágyi út', 'Diósd határ', 'Ipari park'],
    description: 'Fejlődő kisváros Budapest határában, ipari parkokkal.',
    localFact: 'Törökbálint Budapest közelében lévő fejlődő kisváros, ahol az ipari parkok folyamatos munkákat adnak.',
    h1: 'Villanyszerelő Törökbálinton – Helyi Szakember',
    metaTitle: 'Villanyszerelő Törökbálint ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Profi villanyszerelő Törökbálinton ✓ Hibaelhárítás, felújítás ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Milyen gyorsan érnek ki Törökbálintra?', a: 'Sürgős esetben 2-4 óra, egyébként 24 órán belül.' },
      { q: 'Mennyibe kerül a villanyszerelés Törökbálinton?', a: 'Hibaelhárítás 15 000 Ft-tól, felújítás 800-1200 Ft/m²-től.' },
      { q: 'Vállalnak ipari munkákat Törökbálinton?', a: 'Igen, ipari és üzleti ingatlanok is a szakterületünk.' },
      { q: 'Törökbálint melyik részeire szállnak ki?', a: 'Törökbálint teljes területére kiszállunk.' },
      { q: 'Rendelkeznek engedéllyel?', a: 'Igen, minden munkatársunk rendelkezik a szükséges képesítéssel.' },
    ],
  },
  {
    slug: 'villanyszerelo-szigetszentmiklos',
    suffixOn: 'Szigetszentmiklóson',
    suffixAdj: 'szigetszentmiklosi',
    name: 'Szigetszentmiklós',
    county: 'Pest megye',
    population: '39 000',
    mainKeyword: 'villanyszerelő Szigetszentmiklós',
    searchVolume: 70,
    districts: ['Szigetszentmiklós belváros', 'Lakihegy', 'Taksony határ', 'Iparitelep'],
    description: 'Csepel-sziget egyik legnépesebb városa, ipari és lakóterületekkel.',
    localFact: 'Szigetszentmiklós a Csepel-sziget egyik legnépesebb városa, fontos ipari és logisztikai központ.',
    h1: 'Villanyszerelő Szigetszentmiklóson – Gyors Kiszállás',
    metaTitle: 'Villanyszerelő Szigetszentmiklós ✓ Azonnali Kiszállás | Villanymester',
    metaDescription: 'Megbízható villanyszerelő Szigetszentmiklóson ✓ Hibaelhárítás, felújítás ✓ Gyors kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Mennyibe kerül a villanyszerelés Szigetszentmiklóson?', a: 'Hibaelhárítás 15 000 Ft-tól, lakásfelújítás 800-1200 Ft/m²-től.' },
      { q: 'Milyen gyorsan érnek ki?', a: 'Sürgős esetben 2-4 óra, egyébként 24 órán belül.' },
      { q: 'Vállalnak új építést Szigetszentmiklóson?', a: 'Igen, új épületek villanyszerelése is a szakterületünk.' },
      { q: 'Melyik részeire szállnak ki?', a: 'Szigetszentmiklós teljes területére kiszállunk.' },
      { q: 'Rendelkeznek engedéllyel?', a: 'Igen, minden munkatársunk képesített villanyszerelő.' },
    ],
  },
  {
    slug: 'villanyszerelo-vecses',
    suffixOn: 'Vecsésen',
    suffixAdj: 'vecsesi',
    name: 'Vecsés',
    county: 'Pest megye',
    population: '21 000',
    mainKeyword: 'villanyszerelő Vecsés',
    searchVolume: 50,
    districts: ['Vecsés belváros', 'Ferihegy', 'Újtelep', 'Dobó út'],
    description: 'A Liszt Ferenc repülőtér szomszédságában lévő dinamikus kisváros.',
    localFact: 'Vecsés a Liszt Ferenc Nemzetközi Repülőtér közelében található.',
    h1: 'Villanyszerelő Vecsésen – Megbízható Elektromos Munkák',
    metaTitle: 'Villanyszerelő Vecsés ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Profi villanyszerelő Vecsésen ✓ Hibaelhárítás, felújítás, töltő telepítés ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Milyen gyorsan érnek ki Vecsésen?', a: 'Sürgős esetben 2-4 óra, egyébként 24 órán belül.' },
      { q: 'Mennyibe kerül a villanyszerelés Vecsésen?', a: 'Hibaelhárítás 15 000 Ft-tól, felújítás 800-1200 Ft/m²-től.' },
      { q: 'Vállalnak EV töltő telepítést Vecsésen?', a: 'Igen, elektromos autó töltő telepítés is a szolgáltatásaink között van.' },
      { q: 'Vecsés melyik részeire szállnak ki?', a: 'Vecsés teljes területére kiszállunk.' },
      { q: 'Rendelkeznek engedéllyel?', a: 'Igen, minden munkatársunk képesített villanyszerelő.' },
    ],
  },
  {
    slug: 'villanyszerelo-gyal',
    suffixOn: 'Gyálon',
    suffixAdj: 'gyali',
    name: 'Gyál',
    county: 'Pest megye',
    population: '23 000',
    mainKeyword: 'villanyszerelő Gyál',
    searchVolume: 40,
    districts: ['Gyál belváros', 'Újváros', 'Iparitelep', 'Határsor'],
    description: 'Fejlődő Pest megyei kisváros Budapest dél-keleti agglomerációjában.',
    localFact: 'Gyál Budapest dél-keleti agglomerációjának egyik fejlődő kisvárosában sok új lakópark épül.',
    h1: 'Villanyszerelő Gyálon – Helyi Szakember Pest Megyében',
    metaTitle: 'Villanyszerelő Gyál ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Megbízható villanyszerelő Gyálon ✓ Hibaelhárítás, felújítás ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Milyen gyorsan érnek ki Gyálra?', a: 'Sürgős esetben 2-4 óra, egyébként 24 órán belül.' },
      { q: 'Mennyibe kerül a villanyszerelés Gyálon?', a: 'Hibaelhárítás 15 000 Ft-tól, felújítás 800-1200 Ft/m²-től.' },
      { q: 'Vállalnak új építést Gyálon?', a: 'Igen, új épületek és lakóparkok villanyszerelése is a szakterületünk.' },
      { q: 'Gyál melyik részeire szállnak ki?', a: 'Gyál teljes területére kiszállunk.' },
      { q: 'Rendelkeznek engedéllyel?', a: 'Igen, minden munkatársunk képesített villanyszerelő.' },
    ],
  },
]

export const SERVICES = [
  { slug: 'hibaelharitas', name: 'Hibaelhárítás', icon: '⚡', desc: 'Gyors diagnózis és javítás minden elektromos meghibásodásnál.' },
  { slug: 'lakas-felujitas', name: 'Lakás felújítás', icon: '🏠', desc: 'Teljes elektromos rendszer korszerűsítése és felújítása.' },
  { slug: 'elektromos-auto-tolto', name: 'EV Töltő telepítés', icon: '🔌', desc: 'Otthoni és társasházi elektromos autó töltők beszerelése.' },
  { slug: 'napelem-bekotes', name: 'Napelem bekötés', icon: '☀️', desc: 'Napelem rendszerek villanyszerelési munkái, hálózati bekötés.' },
  { slug: 'ipari-villanyszereles', name: 'Ipari villanyszerelés', icon: '🏭', desc: 'Gyárak, irodaházak, kereskedelmi ingatlanok elektromos rendszerei.' },
  { slug: 'okosotthon', name: 'Okosotthon', icon: '🤖', desc: 'Smart home rendszerek telepítése: világítás, riasztó, automatika.' },
]

export const REVIEWS = [
  { name: 'Kovács István', city: 'Érd', stars: 5, text: 'Kiváló munka! Gyorsan kiszálltak, szakszerűen megoldották a problémát. Ajánlom mindenkinek!', date: '2025-03-15' },
  { name: 'Szabó Mária', city: 'Gödöllő', stars: 5, text: 'Elektromos autó töltőt szereltek fel nálunk. Precíz, gyors munka, tisztán hagyták a helyet.', date: '2025-02-28' },
  { name: 'Tóth Péter', city: 'Dunakeszi', stars: 5, text: 'Teljes lakásfelújítás villanyszerelése. Megbízható, pontos, az ár is korrekt volt.', date: '2025-01-20' },
  { name: 'Nagy Éva', city: 'Szentendre', stars: 5, text: 'Régi házunk elektromos rendszerét cserélték le. Profi csapat, tudták mi a dolguk.', date: '2025-02-10' },
  { name: 'Varga László', city: 'Vác', stars: 5, text: 'Sürgős hibaelhárítás, 3 óra alatt kiszálltak. Nagyon megkönnyítették a helyzetünket!', date: '2025-03-01' },
  { name: 'Fekete Zsuzsanna', city: 'Érd', stars: 5, text: 'Napelem rendszer bekötése precízen elvégezve. Minden papír megvolt, ajánlom!', date: '2025-01-05' },
]