export const SITE = {
  name: 'Villanymester',
  tagline: 'Megbízható villanyszerelő Pest megyében',
  domain: 'mateklap.hu',
  url: 'https://mateklap.hu',
  phone: '+36 20 555 7891',
  phoneDisplay: '+36 20 555 7891',
  email: 'info@mateklap.hu',
  address: 'Érd, Pest megye',
  founded: '2015',
  logo: '/logo.svg',
  description: 'Profi villanyszerelési szolgáltatások Pest megyében. Érd, Gödöllő, Dunakeszi, Szentendre, Vác és környéke. Gyors kiszállás, megbízható munka, díjmentes árajánlat.',
}

export const CITIES = [
  {
    slug: 'villanyszerelo-erd',
    suffixOn: 'Érden',
    suffixAdj: 'érdi',
    name: 'Érd',
    county: 'Pest megye',
    population: '70 000',
    mainKeyword: 'villanyszerelő Érd',
    searchVolume: 260,
    districts: ['Érd-Óváros', 'Érd-Parkváros', 'Érd-Ciprusdomb', 'Érd-Újváros'],
    description: 'Pest megye legnépesebb városa, 70 000+ lakos, aktív ingatlanpiac.',
    localFact: 'Érd Pest megye legnépesebb városa közel 70 000 lakossal. Az M0-ás és a 6-os főút mentén elhelyezkedő városban az ingatlanfejlesztések és felújítások folyamatosak.',
    h1: 'Villanyszerelő Érden – Gyors, Megbízható Elektromos Munkák',
    metaTitle: 'Villanyszerelő Érd ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Profi villanyszerelő Érden ✓ Hibaelhárítás, töltő telepítés, felújítás ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most: +36 20 555 7891',
    faqs: [
      { q: 'Milyen gyorsan tud kiszállni villanyszerelő Érden?', a: 'Sürgős megkeresések esetén általában 2-4 órán belül kiszállunk Érd területén. Normál esetben 24 órán belül időpontot tudunk egyeztetni.' },
      { q: 'Mennyibe kerül a villanyszerelés Érden?', a: 'Az árak az elvégzett munka típusától függnek. Hibaelhárítás 15 000 Ft-tól, lakás villanyszerelés 800-1200 Ft/m² áron. Részletes díjmentes árajánlatot adunk.' },
      { q: 'Vállalnak elektromos autó töltő telepítést Érden?', a: 'Igen, a töltő telepítés az egyik legkeresettebb szolgáltatásunk Érden. 11 kW-os fali töltőt 120 000-180 000 Ft-tól telepítünk.' },
      { q: 'Érd melyik részére szállnak ki?', a: 'Érd összes városrészére kiszállunk: Óváros, Parkváros, Ciprusdomb, Újváros és minden érintett terület.' },
      { q: 'Rendelkeznek villanyszerelői engedéllyel?', a: 'Igen, minden munkatársunk rendelkezik a szükséges villanyszerelői képesítéssel és engedéllyel. Munkáinkhoz tűzvédelmi és elektromos bejelentési dokumentumokat adunk.' },
    ],
  },
  {
    slug: 'villanyszerelo-godollö',
    suffixOn: 'Gödöllőn',
    suffixAdj: 'gödöllői',
    name: 'Gödöllő',
    county: 'Pest megye',
    population: '35 000',
    mainKeyword: 'villanyszerelő Gödöllő',
    searchVolume: 190,
    districts: ['Gödöllő belváros', 'Máriabesnyő', 'Erzsébetkert', 'Dózsa György lakótelep'],
    description: 'Élénk egyetemi város, Grassalkovich-kastély, sok felújítandó ingatlan.',
    localFact: 'Gödöllő a Grassalkovich-kastélyáról és a MATE Gödöllői Kampuszáról ismert város. Az élénk ingatlanpiac és a sok régi, felújítandó épület folyamatos elektromos munkákat generál.',
    h1: 'Villanyszerelő Gödöllőn – Profi Elektromos Munkák Garanciával',
    metaTitle: 'Villanyszerelő Gödöllő ✓ Azonnali Kiszállás | Villanymester Kft.',
    metaDescription: 'Megbízható villanyszerelő Gödöllőn ✓ Felújítás, hibaelhárítás, töltő telepítés ✓ Azonnali kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Mennyibe kerül a villanyszerelés Gödöllőn?', a: 'Hibaelhárítás 15 000 Ft-tól, teljes lakás villanyszerelés 800-1200 Ft/m²-től. Részletes ingyenes árajánlatot adunk.' },
      { q: 'Gödöllő melyik részére szállnak ki?', a: 'Gödöllő egész területére kiszállunk: belváros, Máriabesnyő, Erzsébetkert és minden egyéb városrész.' },
      { q: 'Vállalnak munkát régi gödöllői házakban is?', a: 'Igen, tapasztaltak vagyunk régi elektromos rendszerek felújításában és korszerűsítésében.' },
      { q: 'Milyen gyorsan érnek ki Gödöllőre?', a: 'Sürgős esetben 2-4 órán belül, normál esetben 24 órán belüli időpontot tudunk adni.' },
      { q: 'Vállalnak napelem bekötést Gödöllőn?', a: 'Igen, napelem rendszerek villanyszerelési munkáit vállaljuk: bekötés, védelem telepítése, hálózati csatlakozás.' },
    ],
  },
  {
    slug: 'villanyszerelo-dunakeszi',
    suffixOn: 'Dunakeszin',
    suffixAdj: 'dunakeszi',
    name: 'Dunakeszi',
    county: 'Pest megye',
    population: '42 000',
    mainKeyword: 'villanyszerelő Dunakeszi',
    searchVolume: 210,
    districts: ['Dunakeszi belváros', 'Alag', 'Dunakeszi-Gyártelep', 'Tőzeges'],
    description: 'Dinamikusan fejlődő Duna-parti város, sok új lakópark és fejlesztés.',
    localFact: 'Dunakeszi az egyik legdinamikusabban fejlődő Pest megyei város, ahol folyamatosan épülnek új lakóparkok és irodaházak. Ez rengeteg új elektromos munkát generál.',
    h1: 'Villanyszerelő Dunakeszin – Új Építés és Felújítás Specialista',
    metaTitle: 'Villanyszerelő Dunakeszi ✓ Gyors Kiszállás | Villanymester Kft.',
    metaDescription: 'Profi villanyszerelő Dunakeszin ✓ Új építés, felújítás, töltő telepítés ✓ Gyors kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Vállalnak új építésű projektet Dunakeszin?', a: 'Igen, az új építések villanyszerelése az egyik fő szakterületünk Dunakeszin és környékén.' },
      { q: 'Mennyibe kerül a villanyszerelés Dunakeszin?', a: 'Hibaelhárítás 15 000 Ft-tól, új épület villanyszerelés 900-1400 Ft/m²-től. Ingyenes helyszíni felmérést végzünk.' },
      { q: 'Milyen gyorsan lehet időpontot kapni Dunakeszin?', a: 'Sürgős esetben 2-4 óra, normál esetben 24 órán belül.' },
      { q: 'Vállalnak elektromos autó töltő telepítést Dunakeszin?', a: 'Igen, társasházi és egyéni töltő telepítése is a szolgáltatásaink között van.' },
      { q: 'Dunakeszi melyik részére szállnak ki?', a: 'Dunakeszi teljes területére: belváros, Alag, Gyártelep, Tőzeges és minden városrész.' },
    ],
  },
  {
    slug: 'villanyszerelo-szentendre',
    suffixOn: 'Szentendrén',
    suffixAdj: 'szentendrei',
    name: 'Szentendre',
    county: 'Pest megye',
    population: '26 000',
    mainKeyword: 'villanyszerelő Szentendre',
    searchVolume: 170,
    districts: ['Szentendre belváros', 'Izbég', 'Pannónia utca negyed', 'Pismány'],
    description: 'Festői Duna-parti kisváros, sok régi épület és műemlék, turisztikai célpont.',
    localFact: 'Szentendre festői kisváros a Duna-kanyarban, sok régi, felújítandó épülettel. A műemlékes és régi házak villanyszerelése speciális szakértelmet igényel.',
    h1: 'Villanyszerelő Szentendrén – Régi és Új Épületek Specialistája',
    metaTitle: 'Villanyszerelő Szentendre ✓ Régi Házak Specialistája | Villanymester',
    metaDescription: 'Megbízható villanyszerelő Szentendrén ✓ Régi épületek, műemlékes házak felújítása ✓ Gyors kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Dolgoznak régi szentendrei házakban is?', a: 'Igen, tapasztaltak vagyunk régi, műemlékes épületek elektromos rendszereinek felújításában és korszerűsítésében.' },
      { q: 'Mennyibe kerül a villanyszerelés Szentendrén?', a: 'Hibaelhárítás 15 000 Ft-tól, felújítás 900-1300 Ft/m²-től. Ingyenes árajánlat minden munkához.' },
      { q: 'Milyen gyorsan érnek ki Szentendrére?', a: 'Sürgős esetben 2-4 óra, egyébként 24 órán belüli időpont.' },
      { q: 'Vállalnak napelem bekötést Szentendrén?', a: 'Igen, napelem rendszerek bekötése, hálózati csatlakoztatása és védelmi rendszerek kiépítése.' },
      { q: 'Szentendre melyik részére szállnak ki?', a: 'Szentendre teljes területére: belváros, Izbég, Pismány és minden városrész.' },
    ],
  },
  {
    slug: 'villanyszerelo-vac',
    suffixOn: 'Vácon',
    suffixAdj: 'váci',
    name: 'Vác',
    county: 'Pest megye',
    population: '34 000',
    mainKeyword: 'villanyszerelő Vác',
    searchVolume: 150,
    districts: ['Vác belváros', 'Deákvár', 'Hétkápolna', 'Alsóváros'],
    description: 'Történelmi barokk belváros, ipari múlttal rendelkező Duna-parti város.',
    localFact: 'Vác gazdag történelmi barokk belvárossal rendelkező Duna-parti város. A sok régi épület és az aktív ipari negyed folyamatos elektromos munkákat igényel.',
    h1: 'Villanyszerelő Vácon – Ipari és Lakóingatlan Szakértők',
    metaTitle: 'Villanyszerelő Vác ✓ Ipari és Lakás Villanyszerelés | Villanymester',
    metaDescription: 'Profi villanyszerelő Vácon ✓ Ipari és lakóingatlan villanyszerelés ✓ Gyors kiszállás ✓ Díjmentes árajánlat ➤ Hívjon most!',
    faqs: [
      { q: 'Vállalnak ipari villanyszerelést Vácon?', a: 'Igen, ipari és kereskedelmi ingatlanok villanyszerelése is a szakterületünk Vácon és környékén.' },
      { q: 'Mennyibe kerül a villanyszerelés Vácon?', a: 'Lakás villanyszerelés 800-1200 Ft/m²-től, ipari munkák egyedi árajánlat alapján.' },
      { q: 'Milyen gyorsan érnek ki Vácra?', a: 'Sürgős esetben 2-4 óra, normál esetben 24 órán belüli időpont.' },
      { q: 'Foglalkoznak régi váci épületekkel?', a: 'Igen, régi és műemlékes épületek elektromos felújítása is vállalt munkakörünk.' },
      { q: 'Vác melyik részére szállnak ki?', a: 'Vác teljes területére: belváros, Deákvár, Hétkápolna, Alsóváros és minden városrész.' },
    ],
  },
]

export const SERVICES = [
  { slug: 'hibaelharitas', name: 'Hibaelhárítás', icon: '⚡', desc: 'Gyors diagnózis és javítás minden elektromos meghibásodásnál.' },
  { slug: 'lakas-felujitas', name: 'Lakás felújítás', icon: '🏠', desc: 'Teljes elektromos rendszer korszerűsítése és felújítása.' },
  { slug: 'elektromos-auto-tolto', name: 'EV Töltő telepítés', icon: '🔌', desc: 'Otthoni és társasházi elektromos autó töltők beszerelése.' },
  { slug: 'napelem-bekotes', name: 'Napelem bekötés', icon: '☀️', desc: 'Napelem rendszerek villanyszerelési munkái, hálózati bekötés.' },
  { slug: 'ipari-villanyszereles', name: 'Ipari villanyszerelés', icon: '🏭', desc: 'Gyárak, irodaházak, kereskedelmi ingatlanok elektromos rendszerei.' },
  { slug: 'okosotthon', name: 'Okosotthon', icon: '🤖', desc: 'Smart home rendszerek telepítése: világítás, riasztó, automatika.' },
]

export const REVIEWS = [
  { name: 'Kovács István', city: 'Érd', stars: 5, text: 'Kiváló munka! Gyorsan kiszálltak, szakszerűen megoldották a problémát. Ajánlom mindenkinek!', date: '2025-03-15' },
  { name: 'Szabó Mária', city: 'Gödöllő', stars: 5, text: 'Elektromos autó töltőt szereltek fel nálunk. Precíz, gyors munka, tisztán hagyták a helyet.', date: '2025-02-28' },
  { name: 'Tóth Péter', city: 'Dunakeszi', stars: 5, text: 'Teljes lakásfelújítás villanyszerelése. Megbízható, pontos, az ár is korrekt volt.', date: '2025-01-20' },
  { name: 'Nagy Éva', city: 'Szentendre', stars: 5, text: 'Régi házunk elektromos rendszerét cserélték le. Profi csapat, tudták mi a dolguk.', date: '2025-02-10' },
  { name: 'Varga László', city: 'Vác', stars: 5, text: 'Sürgős hibaelhárítás, 3 óra alatt kiszálltak. Nagyon megkönnyítették a helyzetünket!', date: '2025-03-01' },
  { name: 'Fekete Zsuzsanna', city: 'Érd', stars: 5, text: 'Napelem rendszer bekötése precízen elvégezve. Minden papír megvolt, ajánlom!', date: '2025-01-05' },
]
